name: Generate-Snake-Animation

on:
  workflow_dispatch: # execute manually
  schedule: # execute every 12 hours
    - cron: "* */6 * * *"

jobs:      
  snake-animation:
    runs-on: ubuntu-latest
    steps:
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.2.0
        id: snake-gif
        with:
          github_user_name: ElBaraaRadwan
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - name: Publish Snake Animation SVG
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
